---
- hosts: all
  become: true
  tasks:
    - name: Install jump client and pre reqs
      user:
        name: toad
        comment: Because it jumps, get it
        uid: 1001
        shell: /bin/bash
        password: $1$SomeSalt$vn3N2kuXMnfyyhcNSDkv21
    - name: Grab the latest jc binary
      get_url:
        dest: /home/toad/
        url: ftp://anonymous@dc.packet.farm:21/etc/bomgar-pec.bin
