---
- hosts: all
  become: true
  tasks:
    - name: Add the user 'toad'
      user:
        name: toad
        comment: Because it jumps, get it
        uid: 1001
        password: $1$SomeSalt$vn3N2kuXMnfyyhcNSDkv21 
