
---
- hosts: all
  become: true
  tasks:
    - name: check if installed
      stat:
        path: /home/toad/jumpclient/
      register: presentjc
    - name: Kill it with fire
      command: /home/toad/jumpclient/uninstall | yes | head -n 5
      become: yes
      become_user: toad
      when: presentjc.stat.exists == True
